export const products = [
  {
    id: "1",
    title: "Fouros Aunthetic T-shirt",
    description: "Fouros Just Air Breath Authentic T-shirt - NavyBlue",
    price: 30,
    discountPercentage: 12.96,
    rating: 4.69,
    stock: 94,
    amount: 1,
    brand: "Fouros ",
    category: "Clothes",
    type: "men",
    images:
      "https://ng.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/71/267707/1.jpg?4833",
  },

  {
    id: "2",
    title: "Belted overlay",
    description:
      "Sheer Blouse Belted Dress Sheer Blouse Belted Dress. Ruffled neck. Black slip liner. ",
    price: 40,
    discountPercentage: 18.0,
    rating: 4.0,
    stock: 24,
    amount: 1,
    brand: "Maurices Dresses",
    category: "clothes",
    type: "women",
    images:
      "https://the5kshop.com/wp-content/uploads/2019/02/Untitled-design-4-1.jpg",
  },

  {
    id: "3",
    title: "Basic midi dress",
    description:
      "Gotta love a classic black dress, can be styled as casual or glam!",
    price: 43,
    discountPercentage: 10.96,
    rating: 4.6,
    stock: 14,
    amount: 1,
    brand: "Crepe",
    category: "clothes",
    type: "women",
    images:
      "https://the5kshop.com/wp-content/uploads/2018/12/Untitled-design-13.png",
  },

  {
    id: "4",
    title: "Lace Waist Belt ",
    description:
      "Stylish Women Lace Waist Belt Wide Cinch Belts Dress One Size Black",
    price: 33,
    discountPercentage: 22.96,
    rating: 4.9,
    stock: 9,
    amount: 1,
    brand: "sah",
    category: "accessories",
    type: "women",
    images:
      "https://ng.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/61/1506821/1.jpg?8917",
  },

  {
    id: "5",
    title: " Mens Strap Belt-Black",
    description: "Designer Leather Automatic Mens Strap Belt-Black",
    price: 30,
    discountPercentage: 12.96,
    rating: 4.69,
    stock: 24,
    amount: 1,
    brand: "Jga",
    category: "accessories",
    type: "men",
    images:
      "https://ng.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/61/6653931/1.jpg?8993",
  },
  {
    id: "6",
    title: "Gina stretch top",
    description:
      "Pattern: Printed Features: Raglan sleeves, cropped Neckline: Round neck Stretch: Highly stretchy Product",
    price: 40,
    discountPercentage: 8.0,
    rating: 4.09,
    stock: 4,
    amount: 1,
    brand: "gina",
    category: "clothes",
    type: "women",
    images:
      "https://the5kshop.com/wp-content/uploads/2021/09/IMG_5456_Facetune_24-09-2021-10-16-30.jpg",
  },
  {
    id: "7",
    title: "Irregular hem skirt",
    description:
      "Solid Color High Waist Belted Side Zipper Irregular Hem Casual Skirts",
    price: 70,
    discountPercentage: 10.5,
    rating: 4.7,
    stock: 11,
    amount: 1,
    brand: "carsinette",
    category: "clothes",
    type: "women",
    images:
      "https://the5kshop.com/wp-content/uploads/2019/09/Untitled-design-10.jpg",
  },
  {
    id: "8",
    title: "Brand Casual Sports Cropped Pants",
    description:
      "Men's Fashion Brand Casual Sports Cropped Pants-Black Thin Style",
    price: 80,
    discountPercentage: 15.0,
    rating: 4.8,
    stock: 22,
    amount: 1,
    brand: "reux",
    category: "clothes",
    type: "men",
    images:
      "https://ng.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/54/9249201/1.jpg?2544",
  },
  {
    id: "9",
    title: "Beach Sandals",
    description: "Unisex Casual Beach Sandals - Orange",
    price: 30,
    discountPercentage: 5.0,
    rating: 4.0,
    stock: 24,
    amount: 1,
    brand: "nb",
    category: "accessories",
    type: "men",
    images:
      "https://www-konga-com-res.cloudinary.com/w_auto,f_auto,fl_lossy,dpr_auto,q_auto/media/catalog/product/V/X/65603_1654591807.jpg",
  },
  {
    id: "10",
    title: "Jean Jacket",
    description: "Jean Jacket - Half Black And Blue Denim Jean",
    price: 90,
    discountPercentage: 15.0,
    rating: 4.3,
    stock: 22,
    amount: 1,
    brand: "demin",
    category: "clothes",
    type: "men",
    images:
      "https://www-konga-com-res.cloudinary.com/w_auto,f_auto,fl_lossy,dpr_auto,q_auto/media/catalog/product/I/U/203218_1661253088.jpg",
  },
  {
    id: "11",
    title: "Starry Sky Magnetic",
    description:
      "Starry Sky Magnetic Female Wristwatch Waterproof Rhinestone-gold",
    price: 80,
    discountPercentage: 15.0,
    rating: 4.8,
    stock: 6,
    amount: 1,
    brand: "ssk",
    category: "accessories",
    type: "women",
    images:
      "https://www-konga-com-res.cloudinary.com/w_auto,f_auto,fl_lossy,dpr_auto,q_auto/media/catalog/product/W/Y/148832_1567661938.jpg",
  },
  {
    id: "12",
    title: "Basic midi dress",
    description:
      "Men's Fashion Brand Casual Sports Cropped Pants-Black Thin Style",
    price: 40,
    discountPercentage: 18.0,
    rating: 4.4,
    stock: 2,
    amount: 1,
    brand: "tera",
    category: "clothes",
    type: "women",
    images:
      "https://the5kshop.com/wp-content/uploads/2018/12/Untitled-design-13.png",
  },
  {
    id: "13",
    title: "Cufflinks - Black",
    description:
      "Mens Tuxedo Cufflinks and Studs Formal Set in Black Onyx and Silver with Travel Presentation",
    price: 48,
    discountPercentage: 25.0,
    rating: 4.8,
    stock: 11,
    amount: 1,
    brand: "vi",
    category: "accessories",
    type: "men",
    images:
      "https://www-konga-com-res.cloudinary.com/w_auto,f_auto,fl_lossy,dpr_auto,q_auto/media/catalog/product/D/E/102125_1517247709.jpg",
  },
  {
    id: "14",
    title: "patty pink mesh top",
    description: "Pink Print Short Sleeve Longline Boxy Top",
    price: 20,
    discountPercentage: 10.0,
    rating: 4.8,
    stock: 20,
    amount: 1,
    brand: "reux",
    category: "clothes",
    type: "women",
    images: "https://the5kshop.com/wp-content/uploads/2022/07/IMG_5596.jpg",
  },
  {
    id: "15",
    title: "Rele pinafore",
    description: "BlueBouclé Flippy Mini Pinafore Dress",
    price: 23,
    discountPercentage: 10.0,
    rating: 4.8,
    stock: 20,
    amount: 1,
    brand: "crepe",
    category: "clothes",
    type: "women",
    images:
      "https://the5kshop.com/wp-content/uploads/2021/01/8F674C96-6D42-4CB9-9168-0E62A83CA0DA.jpeg",
  },
  {
    id: "16",
    title: "Diamanté Headband",
    description: "Silver Halloween Metal Boo Diamanté Headband",
    price: 5,
    rating: 4.8,
    stock: 10,
    amount: 1,
    brand: "cre",
    category: "accessories",
    type: "women",
    images:
      "https://media3.newlookassets.com/i/newlook/839633192M1/womens/accessories/hair-accessories/silver-halloween-metal-boo-diamante-headband.jpg?strip=true&qlt=80&w=720",
  },
  {
    id: "17",
    title: "Rust Cable Knit Relaxed Fit Jumper",
    description: "Rust Cable Knit Relaxed Fit Jumper",
    price: 29,
    rating: 4.2,
    stock: 3,
    amount: 1,
    brand: "df",
    category: "clothes",
    type: "Men",
    images:
      "https://media3.newlookassets.com/i/newlook/836974924/mens/mens-clothing/mens-jumpers-and-cardigans/rust-cable-knit-relaxed-fit-jumper.jpg?strip=true&qlt=80&w=720",
  },
  {
    id: "18",
    title: "Chelsea Boots",
    description: "Black Chunky Chelsea Boots",
    price: 55,
    rating: 4.2,
    stock: 14,
    amount: 1,
    brand: "chelsea",
    category: "accessories",
    type: "Men",
    images:
      "https://media3.newlookassets.com/i/newlook/832123201/mens/mens-shoes-and-boots/mens-boots/black-chunky-chelsea-boots.jpg?strip=true&qlt=80&w=720",
  },
  {
    id: "19",
    title: "2 Pack Black and Stone Ribbed Fisherman Beanies",
    description: "Get 2 Pack Black and Stone Ribbed Fisherman Beanies",
    price: 15,
    rating: 4.5,
    stock: 6,
    amount: 1,
    brand: "Fdl",
    category: "accessories",
    type: "Men",
    images:
      "https://media3.newlookassets.com/i/newlook/833740599M1/mens/mens-accessories/2-pack-black-and-stone-ribbed-fisherman-beanies.jpg?strip=true&qlt=80&w=720",
  },
  {
    id: "20",
    title: " Backpack",
    description: "Black Laptop Backpack",
    price: 19,
    rating: 4.7,
    stock: 9,
    amount: 1,
    brand: "Fl",
    category: "accessories",
    type: "Men",
    images:
      "https://media2.newlookassets.com/i/newlook/815263701/mens/mens-accessories/black-laptop-backpack.jpg?strip=true&qlt=80&w=720",
  },
];

export default products;
